name: Build and Deploy

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
