name: Deploy

on:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: github-actions
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: /rs-projects/open-live-trivia/api/overrides/start-services.sh
